### ISSUE TITLE
Can't seem to animate changing pages on BmoViewPager

### ISSUE THREAD

**Issue by alejandroivan** [tzef/BmoViewPager#12]
I have a `HomeViewController` in which I have added a `BmoViewPager` (**not** `BmoPageViewController`). It works fine and I can get the current page when I scroll with the finger, using delegate methods.

But I've found a strange behavior. I cannot seem to change the page in an **animated** way. I'm implementing my own `UIPageControl` in which I have a target function this way:

```
@objc func pageControlDidChangePage(_ pageControl: UIPageControl) {
    pagerView.presentedPageIndex = pageControl.currentPage
}
```

So when I tap on the `UIPageControl`, the page should change with it. It does change the page, but that change is not animated. How do I make it animated?

There should be a `func setPresentedPage(index: Int, animated: Bool = false)` to allow us to animate the change. Or am I missing something?

Thanks!

**Comment by tzef** [comment]
Hi, it sounds like issue #8 

If you want to have scroll animation every time, the pageViewController need be initialed before BmoViewPagerDataSource ask it.

In my reality project, 
I create a dictionary `var cachedPageViewControllers = [Int: UIViewController]()`, 
keep the UIViewController of previous page, current page and next page all the time.

**Comment by alejandroivan** [comment]
Thanks for your answer @tzef! Then it should probably be documented.
As `BmoViewPager` view is `IBDesignable`, intuition says it can just be used as a view, just change the class for the view and everything should work.

At least on Storyboard, the only option for the view pager to work at 100% is to use container views, as I see it. Thanks again!
