### ISSUE TITLE
how to return current index and how to divide the 4 tab equally 

### ISSUE THREAD

**Issue by tangjiarao** [tzef/BmoViewPager#2]
1.how to return current index 
2.how to divide the 4 tab equally 

thx'

**Comment by tzef** [comment]
1. you can get current index from BmoViewPager's public variable `presentedPageIndex` or implement `func bmoViewPagerDelegate(_ viewPager: BmoViewPager, pageChanged page: Int)`  of BmoViewPagerDelegate

2. you can assign tab size in `bmoViewPagerDataSourceNaviagtionBarItemSize`, which is an optional function of 'BmoViewPagerDataSource'
for example: return CGSize(width: navigationBar.bounds.width / 4, height: navigationBar.bounds.height)
