### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by mspanadgoo** [tzef/BmoViewPager#20]
Hi,

Thank you for your great pod.
I configured it easily and it worked, you mentioned that it supports RTL but I couldn't find the way to make my view RTL.
I just want to know how can I do this. 

Thank you again.

**Comment by tzef** [comment]
Hi, it should follow system setup automatically
but I just tested it seems broken now, the existing detect way didn't find out it's RTL :(
I will fix it this week, thanks for your report, and glad you're using it :)

**Comment by tzef** [comment]
Hi, I already released the fixed version
feel free to take a try with 5.1.0 and leave comments 🙂

**Comment by mspanadgoo** [comment]
Hi, Thank you for the bug fix.
