### ISSUE TITLE
Navigation bar not focus to the current page

### ISSUE THREAD

**Issue by dev-vinoth** [tzef/BmoViewPager#4]
If have 10 view controllers. then I select 9th one means, it does't focus current title.

viewPagerNavigationBar.autoFocus = true ->  it's support only the page did changed.

help me to fix this.

**Comment by tzef** [comment]
Hi, I can't totally understand it, can you describe in more detail about your process.
Do you want to change the focus title but stay the same page? Or could you provide code sample so that I can reproduce this issue. Thanks!

**Comment by dev-vinoth** [comment]
Ok, Here I have added Bug screen + sample code. So you can reproduce the issue.

 ** Code  Screenshot**
![screen shot 2017-12-02 at 2 53 44 pm](https://user-images.githubusercontent.com/16603533/33514006-27bd3904-d772-11e7-8d72-5a849341e498.png)

 ** Bug View**
> From this screenshot titleView Not focus to the currentPage

![simulator screen shot - iphone 6s - 2017-12-02 at 14 51 03](https://user-images.githubusercontent.com/16603533/33514008-33d13d1c-d772-11e7-84fc-be05b6cf88d0.png)


 ** Sample Code**
IndexPage with BMO delegate& datasource
`class IndexBmoVC: UIViewController, BmoViewPagerDataSource, BmoViewPagerDelegate  {
    
    @IBOutlet weak var viewPagerNavigationBar: BmoViewPagerNavigationBar!
    @IBOutlet weak var viewPager: BmoViewPager!
    
    var selectedIndex: Int!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        viewPager.delegate = self
        viewPager.dataSource = self

        viewPagerNavigationBar.autoFocus = true
        viewPagerNavigationBar.viewPager = viewPager
        
        viewPager.presentedPageIndex = 7 //selectedIndex
    }

    func bmoViewPagerDataSourceNaviagtionBarItemTitle(_ viewPager: BmoViewPager, navigationBar: BmoViewPagerNavigationBar, forPageListAt page: Int) -> String? {
        return "Page \(page)"
    }

    func bmoViewPagerDataSourceNumberOfPage(in viewPager: BmoViewPager) -> Int {
        return 10
    }
    
    func bmoViewPagerDataSource(_ viewPager: BmoViewPager, viewControllerForPageAt page: Int) -> UIViewController {
        
        let PageDetailVC = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "PageDetailVC") as! PageDetailViewController
        PageDetailVC.pageIndex = page
        return PageDetailVC
    }
}`

Sample DetailPage
`class PageDetailViewController: UIViewController {
    
    @IBOutlet weak var titleLabel: UILabel!
    var pageIndex: Int!

    override func viewDidLoad() {
        super.viewDidLoad()

        titleLabel.text = "Selected Page \(pageIndex!)"
    }
}`

Please fix this..

**Comment by tzef** [comment]
Thanks for your report, the issue has been fixed at version 4.0.3, please update it.
