### ISSUE TITLE
iOS 11 adjust ContentSize

### ISSUE THREAD

**Issue by springlo** [tzef/BmoViewPager#5]
when I add the BmoViewPagerNavigationBar to nav titleView, pushed a VC then pop back, the pagerBar did disappeared.

so must add the code to  BmoViewPagerNavigationBar.

```
    /// iOS11 navigationItem.titleView
    public override var intrinsicContentSize: CGSize {
        return frame.size
    }
```

**Comment by tzef** [comment]
thanks for your suggestion, I will update it at next version
