### ISSUE TITLE
swipe from rtl

### ISSUE THREAD

**Issue by k41ed** [tzef/BmoViewPager#6]
i use arabic in app
how to swip from rtl

**Comment by tzef** [comment]
thanks for your suggestion.
4.0.5 have updated, will support Right-to-Left (RTL) User Interface for iOS 9.0 or higher

**Comment by k41ed** [comment]
nice work

**Comment by k41ed** [comment]
can you updated for swift 3 ?

**Comment by tzef** [comment]
It will be too much work for me and there are many commits after I updated to swift 4. Also, I don't have old version Xcode. Although I wanna help you, but I can't do it. Sorry!
